name: 'Kestra Deploy Flows Action'
description: 'Create, update or delete a list of flows from a folder recursively'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  directory:
    description: 'Folder containing your flows'
    default: './'
  server:
    description: 'URL of your Kestra server'
    required: true
  user:
    description: 'User for the basic auth'
    required: false
  password:
    description: 'Password for the basic auth'
    required: false
  delete:
    description: 'If flows not found should be deleted.'
    required: false
    type: boolean
    default: false
  tenant:
    description: 'Tenant identifier (EE only, when multi-tenancy is enabled)'
    required: false
  apiToken:
    description: 'API Token (EE only)'
    required: false
  namespace:
    description: 'Parent namespace of the updated flows. If none are set all namespaces are allowed.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.server }}
    - ${{ inputs.user }}
    - ${{ inputs.password }}
    - ${{ inputs.delete }}
    - ${{ inputs.tenant }}
    - ${{ inputs.apiToken }}
    - ${{ inputs.namespace }}
